platform :ios, '12.0'
use_frameworks!

target 'TrustSDK_Example' do
  project 'TrustSDK'
  pod 'TrustSDK/Wallet', :path => '../'
  pod 'SwiftLint'
  pod 'CryptoSwift'
  target 'TrustSDK_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # remove deployment_target from target level
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
