language: swift
osx_image: xcode10

cache:
  - cocoapods
  - bundler

before_install:
  - pod install --repo-update
  - brew update
  - brew install swiftlint || true

before_script:
  - bundle exec danger

script:
  - set -o pipefail
  - xcodebuild clean test -workspace TrustSDK.xcworkspace -scheme "TrustSDK" -destination 'platform=iOS Simulator,name=iPhone 8' -quiet
  - xcodebuild clean test -workspace TrustSDK.xcworkspace -scheme "TrustSDK" -destination 'platform=iOS Simulator,name=iPhone 5s' -quiet
  - xcodebuild clean test -workspace TrustSDK.xcworkspace -scheme "TrustWalletSDK" -destination 'platform=iOS Simulator,name=iPhone 8' -quiet
  - xcodebuild clean test -workspace TrustSDK.xcworkspace -scheme "TrustWalletSDK" -destination 'platform=iOS Simulator,name=iPhone 5s' -quiet

after_success:
  - bash <(curl -s https://codecov.io/bash)
