#!/bin/bash

set -eo pipefail

VERSION=$1
if [ -z "$VERSION" ]; then
    VERSION=`git describe --long --tags | cut -f 1 -d "-"`
fi

PODSPEC_FILE="/tmp/TrustSDK.podspec"
echo Pushing "$VERSION" "$PODSPEC_FILE"

cat << EOF > "$PODSPEC_FILE"
Pod::Spec.new do |s|
  s.name             = 'TrustSDK'
  s.version          = '$VERSION'
  s.summary          = 'Trust Wallet SDK'
  s.homepage         = 'https://github.com/trustwallet/TrustSDK-iOS'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.authors          = { 'Leone Parise' => 'leoneparise', 'Viktor Radchenko' => 'vikmeup' }
  s.source           = { :git => 'https://github.com/trustwallet/TrustSDK-iOS.git', :tag => s.version.to_s }
  s.ios.deployment_target = '11.0'
  s.swift_version = '5.1'
  s.default_subspec = 'Client'

  s.subspec 'Client' do |cs|
    cs.source_files = 'TrustSDK/Classes/Client/**/*'
    cs.dependency 'TrustWalletCore/Types', '~> 2.3.2'
    cs.dependency 'BigInt'
  end

  s.subspec 'Wallet' do |cs|
    cs.source_files = 'TrustSDK/Classes/Wallet/**/*'
    cs.dependency 'TrustSDK/Client'
  end
end    
EOF

# Upload to Cocoapod
echo "Done. running 'pod trunk push $PODSPEC_FILE'"
pod trunk push --allow-warnings "$PODSPEC_FILE"
