name: TrustSDK CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache
      id: pod_cache
      uses: actions/cache@v1.1.2
      with:
        path: Example/Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
    - name : Pod install
      run: pod install --repo-update
      if: steps.pod_cache.outputs.cache-hit != 'true'
      working-directory: ./Example
    - name: Run Tests
      run: fastlane ios tests
      working-directory: ./Example
